<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CopyButton</name>
   <tag></tag>
   <elementGuidId>48aca07f-7d06-45d4-8771-ee8e748d16a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='PDF']/parent::a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.buttons-copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
