<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CopyButton</name>
   <tag></tag>
   <elementGuidId>5ed694ea-9ca7-42a5-9abc-78d1bfe93284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='PDF']/parent::a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.buttons-copy</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
