<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CopyButton</name>
   <tag></tag>
   <elementGuidId>88c626fe-6420-4918-95d3-66f37f0af0f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.buttons-copy</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='PDF']/parent::a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
