<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FromDate</name>
   <tag></tag>
   <elementGuidId>d5a31c52-f9fa-4c23-a263-e7ec6126e809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#daily1</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
