<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NextButton</name>
   <tag></tag>
   <elementGuidId>e8d0cf4f-381c-4c6c-9d70-c445f478cb94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableLengthAndBTN_next</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
