<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PreviousButton</name>
   <tag></tag>
   <elementGuidId>c19d8dfc-6e29-4563-a540-ce776dcc3cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableLengthAndBTN_previous</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
