<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchInputTxt</name>
   <tag></tag>
   <elementGuidId>1c88056b-30f8-40a4-b2df-58f730502f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableLengthAndBTN_filter>label>input</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
