<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ToDate</name>
   <tag></tag>
   <elementGuidId>48e1c067-ad83-47d3-8a71-8a6bc98b58d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#daily2</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datefrom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
